### ISSUE TITLE
Attach access token using Blazor Wasm/Auth0

### ISSUE THREAD

**Issue by tnking83** [svrooij/KiotaWithDependencyInjection#1]
Hello @svrooij I'm struggling with how to adapt this code for a Blazor Wasm project.  My application uses Auth0 for user authentication. With Refit, I could easily inject the access token and send it with each HTTP request with a HttpMessageHandler. In your example I see that you have an authentication provider that dynamically gets an access token but my app only needs to attach the token on outgoing requests. Hopefully this makes sense.

**Comment by svrooij** [comment]
This seems more an issue with [Kiota authentication](https://learn.microsoft.com/en-us/openapi/kiota/authentication?tabs=csharp&wt.mc_id=SEC-MVP-5004985) then an issue with this sample?

But here is my best effort to explain the issue:

If the client is registered with some access token, the access token has to come from somewhere. Most access tokens are only valid for 1 hour, hence the reason there needs to be a way to get the access token dynamically. You can inject something in the [factory](https://github.com/svrooij/KiotaWithDependencyInjection/blob/main/KiotaWithDependencyInjection/Spotify/SpotifyFactory.cs) that has access to the runtime access token.

Or if you must, you could register a class that implements the [IAccessTokenProvider](https://github.com/svrooij/KiotaWithDependencyInjection/blob/main/KiotaWithDependencyInjection/Spotify/SpotifyAccessTokenProvider.cs), register that as a **Singleton** in dependency injection, and do something like:

```csharp
@inject YourSingletonAccessTokenProvider atp;
@inject YourKiotaClient client;
...

apt.SetAccessToken("yourTokenFromSomewhere");
var result = await client.....();
```
